# ChatFun â€” Fun chat games plugin, completely free and open-source!
# ~ made by Olafcio
# > https://modrinth.com/plugin/chatfun

interval: 60 # in seconds, overrideable
max-time: 20 # in seconds, overrideable

min-players: 2 # overrideable
categories: # [!] non-overrideable
  items: true
  blocks: true
  effects: true
  biomes: true
  advancements: true

games:
  unscramble:
    enabled: true
    message: |-
      &7&m{ *100%}&r
      &6<center>&lCHAT GAME&6</center>&r
      &6<center>&m         &r</center>
      &6<center>Unscramble the name:</center>&r
      &6<center>&n{{key}}&r</center>
      &7&m{ *100%}&r

    overrides: {}

  repeat:
    enabled: true
    message: |-
      &7&m{ *100%}&r
      &6<center>&lCHAT GAME&6</center>&r
      &6<center>&m         &r</center>
      &6<center>Repeat the word:</center>&r
      &6<center>&n{{key}}&r</center>
      &7&m{ *100%}&r

    settings:
      key-alphabet: QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm0123456789
      key-length:
        min: 7
        max: 10
    overrides: {}

response-polling-rate: 0.5 # in seconds, overrideable
correct-message: |- # overrideable
  &7&m{ *100%}&r
  &6<center>&lCORRECT ANSWER&6</center>&r
  &6<center>&m              &r</center>
  &6<center>&l{{player}}&6 got it right!</center>
  &7&m{ *100%}&r
miss-message: |- # overrideable
  &7&m{ *100%}&r
  &6<center>&lNO ANSWER&6</center>&r
  &6<center>&m         &r</center>
  &6<center>The answer was:</center>
  &6<center>&l{{key}}&r</center>
  &7&m{ *100%}&r
