# ChatFun â€” Fun chat games plugin, completely free and open-source!
# ~ made by Olafcio
# > https://modrinth.com/plugin/chatfun

interval: 60 # in seconds, overrideable
max-time: 20 # in seconds, overrideable

min-players: 2 # overrideable
categories: # [!] non-overrideable
  items: true
  blocks: true
  effects: true
  biomes: true
  advancements: true

games:
  unscramble:
    enabled: true
    message: |-
      &7&m                   &r
      &6<center>&lCHAT GAME&6</center>&r
      &6<center>&m         </center>&r
      &6<center>Unscramble the word:</center>&r
      &6<center>&n{{key}}</center>&r
      &7&m                   &r

    overrides: {}

response-polling-rate: 0.5 # in seconds, overrideable
correct-message: |- # overrideable
  &7&m                   &r
  &6<center>&lCORRECT ANSWER&6</center>&r
  &6<center>&m         </center>&r
  &6<center>&l{{player}}&6 got it right!</center>&r
  &7&m                   &r
miss-message: |- # overrideable
  &7&m                   &r
  &6<center>&lNO ANSWER&6</center>&r
  &6<center>&m         </center>&r
  &6<center>The answer was:</center>&r
  &6<center>&l{{key}}</center>&r
  &7&m                   &r
